### PR TITLE
Add dark mode (w/ nicer toggle)

### PR DESCRIPTION
**Pull request by ongyx**
Polished enough?

### CODE REVIEW

**Comment by dartraiden** [comment]
Does not work in Firefox (tested on Firefox 85 under Windows 10)

firefox_hYbAwn0SLO

**Comment by ongyx** [comment]
I've added a workaround for Firefox:
Screenshot (8)

Tested on version 85.0.1, Debian 10

**Comment by amitmerchant1990** [comment]
@ongyx Would you be able to move the toggle right next to the "About" link in the navigation menu?

**Comment by ongyx** [comment]
Okay, I moved the toggle beside the navbar and added a moon icon to show dark mode:
record

**Comment by amitmerchant1990** [comment]
There is something still missing in the toggle.

image

**Comment by ongyx** [comment]
Actually, font-awesome was not needed for the toggle, so I'll remove it.

@amitmerchant1990 What browser are you using? I tested the toggle on both Chrome (88.0.4324.150) and Firefox (85.0.1).

**Comment by amitmerchant1990** [comment]
I've tested it on Chrome 87 on Ubuntu 18.04.

**Pull request closed without merging**
